# Generated by Django 2.0 on 2018-07-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default=0)),
                ('fecha_inicio_politica', models.DateTimeField(verbose_name='fecha de inicio en la política')),
            ],
        ),
    ]
