# Generated by Django 2.0 on 2018-08-01 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='edad',
        ),
        migrations.AddField(
            model_name='candidato',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='fecha_inicio_politica',
            field=models.DateField(),
        ),
    ]
